import { Inter } from 'next/font/google'
import { Providers } from './providers'
import { Nav } from './Nav/navbar'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Prototipo',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Nav />
          {children}
        </Providers> 
      </body>
    </html>
  )
}
